### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dieghernan** [rOpenSpain/climaemet#2]
Future workstreams:

# To tackle
- [x] ❗️Use environment variable for API KEY
- [x] Fully adoption of [tidyverse](https://www.tidyverse.org/)
- [x] Fields parsed to proper classes [**Breaking¿?**]
- [x] Review dependencies 
- [x] Refactor code
- [x] Centralise API calls
- [x] Move documentation to pure Markdown 
- [ ] Include tests
- [x] Include example datasets

# Enhacements
- [x] [Major version] Convert objects to `sf`
- [ ] Include new functions to cover more API endpoints

**Comment by dieghernan** [comment]
Test moved to its own issue.

New API endpoints are not completely clear, could be explored on:

https://opendata.aemet.es/dist/index.html
